In [2]:
import numpy as np
array = np.arange(9)
print((array.shape))
print(array)
print(type(array.shape))

(9,)
[0 1 2 3 4 5 6 7 8]
<class 'tuple'>


In [9]:
#array is mutable
array[3]=3
print(array)

[0 1 2 3 4 5 6 7 8]


In [10]:
x=array.reshape(3,3)
print(array)
print(x)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(11,75,3)

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59,
       62, 65, 68, 71, 74])

In [21]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.full((3,2),3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [23]:
np.ones((2,1))

array([[1.],
       [1.]])

In [8]:
samplelist =[1,2,3,4,5,6,7,8]
arr = np.array(samplelist)
print(arr)
print(samplelist)

[1 2 3 4 5 6 7 8]
[1, 2, 3, 4, 5, 6, 7, 8]


In [22]:
max=  arr.max()
mean= arr.mean()
min= arr.min()
print(max,min,mean)
arr=arr.reshape(2,4)
print(arr)
std=arr.std(axis=1)
print(std)

8 1 4.5
[[1 2 3 4]
 [5 6 7 8]]
[1.11803399 1.11803399]


In [25]:
num=[]
for i in range(0,10):
    num.append(np.random.randint(1,10))
num = np.array(num)
print(num)
print(np.unique(num))   

[4 9 4 8 9 4 9 2 8 9]
[2 4 8 9]


In [3]:
x= np.arange(1,4)
y=np.arange(1,7,2)
print(x)
print(y)
print(np.add(x,y))


[1 2 3]
[1 3 5]
[2 5 8]
